-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT*p.PRICE) TOTAL_SALES
FROM FOOD_PRODUCT p
INNER JOIN FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE EXTRACT(YEAR FROM o.PRODUCE_DATE)='2022' AND EXTRACT(MONTH FROM o.PRODUCE_DATE)='05'
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC;